# country_currency.py

country_currency = {
    "afghanistan": "Afghan Afghani (AFN)",
    "albania": "Albanian Lek (ALL)",
    "algeria": "Algerian Dinar (DZD)",
    "andorra": "Euro (EUR)",
    "angola": "Angolan Kwanza (AOA)",
    "argentina": "Argentine Peso (ARS)",
    "australia": "Australian Dollar (AUD)",
    "austria": "Euro (EUR)",
    "bangladesh": "Bangladeshi Taka (BDT)",
    "belgium": "Euro (EUR)",
    "brazil": "Brazilian Real (BRL)",
    "canada": "Canadian Dollar (CAD)",
    "china": "Chinese Yuan (CNY)",
    "france": "Euro (EUR)",
    "germany": "Euro (EUR)",
    "india": "Indian Rupee (INR)",
    "indonesia": "Indonesian Rupiah (IDR)",
    "iran": "Iranian Rial (IRR)",
    "iraq": "Iraqi Dinar (IQD)",
    "ireland": "Euro (EUR)",
    "israel": "Israeli New Shekel (ILS)",
    "italy": "Euro (EUR)",
    "japan": "Japanese Yen (JPY)",
    "kenya": "Kenyan Shilling (KES)",
    "mexico": "Mexican Peso (MXN)",
    "nepal": "Nepalese Rupee (NPR)",
    "netherlands": "Euro (EUR)",
    "new zealand": "New Zealand Dollar (NZD)",
    "nigeria": "Nigerian Naira (NGN)",
    "norway": "Norwegian Krone (NOK)",
    "pakistan": "Pakistani Rupee (PKR)",
    "philippines": "Philippine Peso (PHP)",
    "poland": "Polish Zloty (PLN)",
    "portugal": "Euro (EUR)",
    "qatar": "Qatari Riyal (QAR)",
    "russia": "Russian Ruble (RUB)",
    "saudi arabia": "Saudi Riyal (SAR)",
    "singapore": "Singapore Dollar (SGD)",
    "south africa": "South African Rand (ZAR)",
    "south korea": "South Korean Won (KRW)",
    "spain": "Euro (EUR)",
    "sri lanka": "Sri Lankan Rupee (LKR)",
    "sweden": "Swedish Krona (SEK)",
    "switzerland": "Swiss Franc (CHF)",
    "thailand": "Thai Baht (THB)",
    "turkey": "Turkish Lira (TRY)",
    "united arab emirates": "UAE Dirham (AED)",
    "united kingdom": "Pound Sterling (GBP)",
    "united states": "US Dollar (USD)",
    "vietnam": "Vietnamese Dong (VND)",
    # ...and all remaining countries
}
